### ISSUE TITLE
Normal move 730gb limit counter does not reset

### ISSUE THREAD

**Issue by 3daystoday** [MHA-Team/PTS-Team#15]
I'm running PTS with normal move which have a counter upload counter set to 730gb, after that it pauses the upload. The problem is that the counter does not reset after 24h.

I'm normally at about 150-200gb upload per day, so after a few days I get the message that the upload have paused due to the limit. So i manually have to restart the uploader container to get it going again.

![image](https://user-images.githubusercontent.com/45686348/73534234-eb90d080-4420-11ea-8573-ffc7baa9f12f.png)

**Comment by Hawkinzzz** [comment]
This was fixed yesterday by PhysK (18 hours ago). You just nee dot wait for ouroboros to update the docker.

https://gitlab.com/physk/rclone-unionfs-mount/commit/4c92e8ee4393800929b4c6fc18be793adfcb39ec#6e72f432d97d5ce12c961b609b08c1b8fa2cfd18

**Comment by physk** [comment]
So basically,

integer expression expected -
I forgot to get the script to get it to remove the file, so on every loop it was trying to take the amount off of the total uploaded amount

upload not resetting -
same issue as above, as it was failing to do the math, it wasn't updating the total uploaded amount.

Once the container has updated. i will take about 24 hrs to settle down properly.

or you can `rm -fr /opt/appdata/uploader/vars/gdrive/*` to reset all the files :)
