### ISSUE TITLE
MHA-Team Discord request. [Off topic]

### ISSUE THREAD

**Issue by CyberPoison** [MHA-Team/PTS-Team#21]
Hello, i would like to get some information about what happened with some developers of early PTS-Team like MrDoob i ask it because i doesn't can see her github profile, and i would like to ask if MHA is planing to have a discord server because the others is completely off or disabled.

Regards

**Comment by pazport** [comment]
MrDoob just went KIA for some reason. and MHA are till using the same discord server https://discord.gg/9WkF4H . i a on it now
