### ISSUE TITLE
Uploader run in Loop.

### ISSUE THREAD

**Issue by CyberPoison** [MHA-Team/PTS-Team#22]
The Issue i have is when i try to send a file to my tdrive, when i try to send any file it create a file like
exemple.lock and the uploader goes crazy (Many loops, don't delete files after moving, and in most times the uploader doesn't send the file,...)

This is some of info i can give.

`
[Uploader] Finished looking for files, sleeping 5 secs

[Uploader] Files found to upload

[Uploader] Lock File found for /move/Films[FR]/555.txt

[Uploader] Finished looking for files, sleeping 5 secs

[Uploader] Files found to upload

[Uploader] Lock File found for /move/Films[FR]/555.txt

[Uploader] Finished looking for files, sleeping 5 secs

[Uploader] Files found to upload

[Uploader] Lock File found for /move/Films[FR]/555.txt

[Uploader] Finished looking for files, sleeping 5 secs

[Uploader] [Upload] Upload complete for /move/Films[FR]/555.txt, Cleaning up

[Uploader] Files found to upload

[Uploader] Starting upload of /move/Films[FR]/555.txt

[Uploader] [Upload] Upload started for /move/Films[FR]/555.txt using GDSA01C

[Uploader] GDSA01 is now .00000001862645149230

[Uploader] Sleeping 5s before looking at next file

[Uploader] [Upload] Uploading /move/Films[FR]/555.txt to GDSA01C

`

![image](https://user-images.githubusercontent.com/60718477/74097504-f5938d00-4b0c-11ea-9592-d95cc145dd78.png)

Server Hosted on Hetzner.
EX-52-NVME

**Comment by DomGrieco** [comment]
Maikash will fix it np

**Comment by thesammykins** [comment]
Closing stale issues, if still an issue reopen.
