### ISSUE TITLE
PAS doesnt work anymore

### ISSUE THREAD

**Issue by mondychan** [MHA-Team/PTS-Team#25]
hello

with the latest image of PAS "sabrsorensen/alpine-plex_autoscan:latest" commited to github at 7/23/2020 at 9:52 am (dunno the timezone github uses, if it uses my default then its CET) -  DIGEST = (2247ea93f9d4)

PAS starts to throw error 

![2020-07-23_20-04-35](https://user-images.githubusercontent.com/5130453/88330305-7f39be80-cd2b-11ea-8031-dc40e4eedd39.png)

can be fixed with editing the binding inside the docker container for /rclone_config to

![2020-07-23_21-04-17](https://user-images.githubusercontent.com/5130453/88330379-9aa4c980-cd2b-11ea-84c5-31a09750c20c.png)

and edit the rclone config entry in the file
/opt/appdata/plexautoscan/config/config.json
to
"CONFIG": "/rclone_config/rclone.conf",

fixes the issue

could anyone incorporate this workaround into the deployment code?

**Comment by dallensmith** [comment]
same issue here

**Comment by smashingtags** [comment]
Will look at this shortly am at the beach atm, thanks guys

**Comment by pazport** [comment]
mine as done the update last night. and now. i can't access it on web-browser. but it is still sending signal to plex for time being. so i restarted plexautoscan and now. it just keeps saying i don't have PAS setup

**Comment by smashingtags** [comment]
> hello
> 
> with the latest image of PAS "sabrsorensen/alpine-plex_autoscan:latest" commited to github at 7/23/2020 at 9:52 am (dunno the timezone github uses, if it uses my default then its CET) - DIGEST = (2247ea93f9d4)
> 
> PAS starts to throw error
> 
> ![2020-07-23_20-04-35](https://user-images.githubusercontent.com/5130453/88330305-7f39be80-cd2b-11ea-8031-dc40e4eedd39.png)
> 
> can be fixed with editing the binding inside the docker container for /rclone_config to
> 
> ![2020-07-23_21-04-17](https://user-images.githubusercontent.com/5130453/88330379-9aa4c980-cd2b-11ea-84c5-31a09750c20c.png)
> 
> and edit the rclone config entry in the file
> /opt/appdata/plexautoscan/config/config.json
> to
> "CONFIG": "/rclone_config/rclone.conf",
> 
> fixes the issue
> 
> could anyone incorporate this workaround into the deployment code?

I have tried to implement this fix, working from the beach so much appreciated if you guys can test and make sure I got it right. Then I can close out this issue.

**Comment by mondychan** [comment]
when you recreate the container now, it creates an internal storage for /config binding, instead of the "Regular" "/opt/appdata/plexautoscan/config" binding to "/config" , so the log now shows "no config.json found" error

![2020-07-25_10-30-49](https://user-images.githubusercontent.com/5130453/88452882-9fb86480-ce62-11ea-94d1-6131db5393cf.png)
![2020-07-25_10-31-56](https://user-images.githubusercontent.com/5130453/88452884-a0e99180-ce62-11ea-9622-810f891e6009.png)

after fixing this lil hiccup to the regular binding path, it works, so the other problem with rclone.conf has been fixed :slight_smile:
![2020-07-25_10-33-35](https://user-images.githubusercontent.com/5130453/88452889-a5ae4580-ce62-11ea-84dc-eaa55dd48ec0.png)

tho i would advise (not rly sure if it matters, but better be safe than sorry) to make this binding read-only
![2020-07-25_10-30-41](https://user-images.githubusercontent.com/5130453/88452892-a8109f80-ce62-11ea-958e-70c977ae52a4.png)

**Comment by smashingtags** [comment]
Should be all good now worked for me no errors
