### ISSUE TITLE
unable to set how many files uploaded at once and upload speed

### ISSUE THREAD

**Issue by hiragashi** [MHA-Team/PTS-Team#26]
Unable to specify how many files are uploaded at once.
Also unable to specifiy how fast the upload speed is.

Any ideas how to fix this? it currently uploads 4 at once completely maxing out my bandwidth

**Comment by thesammykins** [comment]
This is by design, the concept of PTS is to be used to upload all day, everyday at maximum speed. 

You may want to look at rolling your own solution or investigating other projects that might better suit your needs, especially when used on low bandwidth connections.
