### ISSUE TITLE
[Action Required] Drive API requires updates to your code before Sep 13, 2021

### ISSUE THREAD

**Issue by daveftw84** [MHA-Team/PTS-Team#28]
Please tell me there's a solution

**Comment by gurabli** [comment]
I hope so too. If not, PTS will brake after Sep 13?

**Comment by dallensmith** [comment]
where are you guys seeing this?

**Comment by thesammykins** [comment]
There's nothing we need to do relating to this. Closing.

https://support.google.com/drive/answer/10729743?p=update_drives_user&visit_id=637659884039350566-1696984815&rd=1
